# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzFSTHPMbVY6qBOrm1jMx-AHkolEu5UA
"""

def trap(height):
    if not height:
        return 0

    left, right = 0, len(height)-1
    left_max, right_max = height[left], height[right]
    volume = 0
    while left < right:
        left_max, right_max = max(left_max, height[left]), max(right_max, height[right])
        if height[left] <= height[right]:
            volume += left_max - height[left]
            left += 1
        else:
            volume += right_max - height[right]
            right -= 1
    return volume

trap([0,1,2,3,4,2,3,1])

trap([0,1,1,0,8,2,4,3,1])

trap([0,2,0,3,1])